### ISSUE TITLE
Remove `sleep` in favor of async/await

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-video-reporter#66]
**Describe the bug**
Putting the process to an halt with:
```js
    const stop = new Date().getTime() + ms;
    while(new Date().getTime() < stop);
```

is not ideal as it completely blocks everything from happening. We should replace this and all functions with proper async/await logic. I see similar implementations in all `do { ... } while (...)` places.

**Log**
n/a

**To Reproduce**
n/a

**Expected behavior**
Use `async/await` instead of this.

**Environment (please complete the following information):**
 - **wdio-video-reporter version:** [e.g. 1.1.2]
 - **WebdriverIO version:** [e.g. 5.4.13]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [e.g. 8.11.2]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wadjei** [comment]
To outline the two PR references above, it turns out that the sleep step is only needed in the onExit code path which is called via `process.on('exit')` (Node event handler).

However, Node requires that all event handlers be called synchronously so an async wait is not possible. Since the halting sleep is only ever done after the suite has completed it's probably best to leave things as they are.

The affected code in onExit is used to trigger the resolution of video file placeholder attachment contents (created in `allure-raw`) from expected file-paths to the actual mp4 video data. This process was refactored in commit #[ed5db47](https://github.com/webdriverio-community/wdio-video-reporter/pull/24/commits/ed5db47a8b4a2b1f4250da84b1e40d32332ceab8) as part of #24 , apparently to resolve an issue where `onRunnerEnd` was being skipped.

**Comment by christian-bromann** [comment]
Thanks for addressing this, I would say this is a good resolution for now and I will go ahead and close this.
